[/]
animate-app-switch=false
animate-appicon-hover=false
animate-appicon-hover-animation-extent={'RIPPLE': 4, 'PLANK': 4, 'SIMPLE': 1}
animate-window-launch=false
appicon-margin=2
appicon-padding=4
appicon-style='NORMAL'
context-menu-entries='[{"title":"Terminal","cmd":"TERMINALSETTINGS"},{"title":"System monitor","cmd":"gnome-system-monitor"},{"title":"Files","cmd":"nautilus"},{"title":"Extensions","cmd":"gnome-extensions-app"}]'
desktop-line-custom-color='rgba(200,200,200,0.2)'
desktop-line-use-custom-color=false
dot-position='BOTTOM'
dot-style-focused='SEGMENTED'
dot-style-unfocused='DOTS'
extension-version=73
focus-highlight=true
global-border-radius=0
group-apps=true
highlight-appicon-hover=true
highlight-appicon-hover-border-radius=0
hotkeys-overlay-combo='TEMPORARILY'
intellihide=false
leftbox-padding=0
panel-anchors='{"SHP-0x00000000":"MIDDLE"}'
panel-element-positions='{"SHP-0x00000000":[{"element":"showAppsButton","visible":true,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":false,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"centerMonitor"},{"element":"centerBox","visible":false,"position":"centerMonitor"},{"element":"rightBox","visible":false,"position":"stackedBR"},{"element":"dateMenu","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":true,"position":"stackedBR"}]}'
panel-lengths='{"SHP-0x00000000":100}'
panel-positions='{"SHP-0x00000000":"BOTTOM"}'
panel-side-margins=0
panel-sizes='{"SHP-0x00000000":40}'
prefs-opened=false
progress-show-count=true
show-apps-icon-file=''
show-favorites-all-monitors=true
show-running-apps=true
show-showdesktop-delay=1000
show-showdesktop-hover=false
show-showdesktop-time=300
show-tooltip=false
show-window-previews=false
showdesktop-button-width=8
status-icon-padding=0
trans-bg-color='#3584e4'
trans-border-width=1
trans-panel-opacity=0.90000000000000002
trans-use-border=false
trans-use-custom-bg=false
trans-use-custom-opacity=true
trans-use-dynamic-opacity=true
tray-padding=0
window-preview-title-position='TOP'
