[/]
settings-version=2

[applications]
blur=false
corner-when-maximized=false
dynamic-opacity=true
enable-all=false
opacity=215
pipeline='pipeline_default'
static-blur=true
whitelist=['Gnome-terminal']

[coverflow-alt-tab]
pipeline='pipeline_default'

[dash-to-dock]
pipeline='pipeline_default_rounded'

[lockscreen]
pipeline='pipeline_default'

[overview]
pipeline='pipeline_default'

[panel]
pipeline='pipeline_default'

[screenshot]
pipeline='pipeline_default'
